<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            'role' => 'admin',
            'name' => 'Admin',
            'username' => 'admin',
            'password' => bcrypt('admin'),
            'himpunan' => 'Mipa',
            'placeofbirth' => 'Jatinangor',
            'dateofbirth' => '-',
            'gender' => '-',
            'email' => '-',
            'phone_number' => '-',
            'phone_number_guardians' => '-',
            'religion' => '-',
            'address' => '-',
            'address_2' => '-',
            'tk' => '-',
            'sd' => '-',
            'smp' => '-',
            'sma' => '-',
            'organization' => '-',
            'committee' => '-',
            'development' => '-',
            'achievement' => '-',
        ]);
        DB::table('users')->insert([
            'role' => 'admin',
            'name' => 'Dekanat',
            'username' => 'dekanat',
            'password' => bcrypt('dekanat'),
            'himpunan' => 'Mipa',
            'placeofbirth' => 'Jatinangor',
            'dateofbirth' => '-',
            'gender' => '-',
            'email' => '-',
            'phone_number' => '-',
            'phone_number_guardians' => '-',
            'religion' => '-',
            'address' => '-',
            'address_2' => '-',
            'tk' => '-',
            'sd' => '-',
            'smp' => '-',
            'sma' => '-',
            'organization' => '-',
            'committee' => '-',
            'development' => '-',
            'achievement' => '-',
        ]);
        DB::table('users')->insert([
            'role' => 'himpunan',
            'name' => 'Himatika',
            'username' => 'himatika',
            'password' => bcrypt('himatika'),
            'himpunan' => 'Himatika',
            'placeofbirth' => 'Jatinangor',
            'dateofbirth' => '-',
            'gender' => '-',
            'email' => '-',
            'phone_number' => '-',
            'phone_number_guardians' => '-',
            'religion' => '-',
            'address' => '-',
            'address_2' => '-',
            'tk' => '-',
            'sd' => '-',
            'smp' => '-',
            'sma' => '-',
            'organization' => '-',
            'committee' => '-',
            'development' => '-',
            'achievement' => '-',
        ]);
        DB::table('users')->insert([
            'role' => 'himpunan',
            'name' => 'Himaka',
            'username' => 'himaka',
            'password' => bcrypt('himaka'),
            'himpunan' => 'Himaka',
            'placeofbirth' => 'Jatinangor',
            'dateofbirth' => '-',
            'gender' => '-',
            'email' => '-',
            'phone_number' => '-',
            'phone_number_guardians' => '-',
            'religion' => '-',
            'address' => '-',
            'address_2' => '-',
            'tk' => '-',
            'sd' => '-',
            'smp' => '-',
            'sma' => '-',
            'organization' => '-',
            'committee' => '-',
            'development' => '-',
            'achievement' => '-',
        ]);
        DB::table('users')->insert([
            'role' => 'himpunan',
            'name' => 'Hifi',
            'username' => 'hifi',
            'password' => bcrypt('hifi'),
            'himpunan' => 'Hifi',
            'placeofbirth' => 'Jatinangor',
            'dateofbirth' => '-',
            'gender' => '-',
            'email' => '-',
            'phone_number' => '-',
            'phone_number_guardians' => '-',
            'religion' => '-',
            'address' => '-',
            'address_2' => '-',
            'tk' => '-',
            'sd' => '-',
            'smp' => '-',
            'sma' => '-',
            'organization' => '-',
            'committee' => '-',
            'development' => '-',
            'achievement' => '-',
        ]);
        DB::table('users')->insert([
            'role' => 'himpunan',
            'name' => 'Himbio',
            'username' => 'himbio',
            'password' => bcrypt('himbio'),
            'himpunan' => 'Himbio',
            'placeofbirth' => 'Jatinangor',
            'dateofbirth' => '-',
            'gender' => '-',
            'email' => '-',
            'phone_number' => '-',
            'phone_number_guardians' => '-',
            'religion' => '-',
            'address' => '-',
            'address_2' => '-',
            'tk' => '-',
            'sd' => '-',
            'smp' => '-',
            'sma' => '-',
            'organization' => '-',
            'committee' => '-',
            'development' => '-',
            'achievement' => '-',
        ]);
        DB::table('users')->insert([
            'role' => 'himpunan',
            'name' => 'Himasta',
            'username' => 'himasta',
            'password' => bcrypt('himasta'),
            'himpunan' => 'Himasta',
            'placeofbirth' => 'Jatinangor',
            'dateofbirth' => '-',
            'gender' => '-',
            'email' => '-',
            'phone_number' => '-',
            'phone_number_guardians' => '-',
            'religion' => '-',
            'address' => '-',
            'address_2' => '-',
            'tk' => '-',
            'sd' => '-',
            'smp' => '-',
            'sma' => '-',
            'organization' => '-',
            'committee' => '-',
            'development' => '-',
            'achievement' => '-',
        ]);
        DB::table('users')->insert([
            'role' => 'himpunan',
            'name' => 'Pedra',
            'username' => 'pedra',
            'password' => bcrypt('pedra'),
            'himpunan' => 'Pedra',
            'placeofbirth' => 'Jatinangor',
            'dateofbirth' => '-',
            'gender' => '-',
            'email' => '-',
            'phone_number' => '-',
            'phone_number_guardians' => '-',
            'religion' => '-',
            'address' => '-',
            'address_2' => '-',
            'tk' => '-',
            'sd' => '-',
            'smp' => '-',
            'sma' => '-',
            'organization' => '-',
            'committee' => '-',
            'development' => '-',
            'achievement' => '-',
        ]);
        DB::table('users')->insert([
            'role' => 'himpunan',
            'name' => 'Himatif',
            'username' => 'himatif',
            'password' => bcrypt('himatif'),
            'himpunan' => 'Himatif',
            'placeofbirth' => 'Jatinangor',
            'dateofbirth' => '-',
            'gender' => '-',
            'email' => '-',
            'phone_number' => '-',
            'phone_number_guardians' => '-',
            'religion' => '-',
            'address' => '-',
            'address_2' => '-',
            'tk' => '-',
            'sd' => '-',
            'smp' => '-',
            'sma' => '-',
            'organization' => '-',
            'committee' => '-',
            'development' => '-',
            'achievement' => '-',
        ]);
        DB::table('users')->insert([
            'role' => 'himpunan',
            'name' => 'Hmte',
            'username' => 'hmte',
            'password' => bcrypt('hmte'),
            'himpunan' => 'Hmte',
            'placeofbirth' => 'Jatinangor',
            'dateofbirth' => '-',
            'gender' => '-',
            'email' => '-',
            'phone_number' => '-',
            'phone_number_guardians' => '-',
            'religion' => '-',
            'address' => '-',
            'address_2' => '-',
            'tk' => '-',
            'sd' => '-',
            'smp' => '-',
            'sma' => '-',
            'organization' => '-',
            'committee' => '-',
            'development' => '-',
            'achievement' => '-',
        ]);
        DB::table('users')->insert([
            'role' => 'himpunan',
            'name' => 'Himaktu',
            'username' => 'himaktu',
            'password' => bcrypt('himaktu'),
            'himpunan' => 'Himaktu',
            'placeofbirth' => 'Jatinangor',
            'dateofbirth' => '-',
            'gender' => '-',
            'email' => '-',
            'phone_number' => '-',
            'phone_number_guardians' => '-',
            'religion' => '-',
            'address' => '-',
            'address_2' => '-',
            'tk' => '-',
            'sd' => '-',
            'smp' => '-',
            'sma' => '-',
            'organization' => '-',
            'committee' => '-',
            'development' => '-',
            'achievement' => '-',
        ]);
    }
}
